version: 2
jobs:

  build:
    docker:
      - image: hanieh/dotnetcore-aws-cli-docker-ce
    environment:
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      # For security purposes, circleci requires this step to isolate remote docker commands. 
      # More info at: https://circleci.com/docs/2.0/building-docker-images/
      - setup_remote_docker
      # Login to AWS with IAM credentials
      - run: eval "$(aws ecr get-login --no-include-email --region ap-southeast-2)"
      - run: docker build -t dotnetcorehelloworld:$CIRCLE_BUILD_NUM .
      # Tag image with version
      - run:  docker tag dotnetcorehelloworld:$CIRCLE_BUILD_NUM 200053207227.dkr.ecr.ap-southeast-2.amazonaws.com/dotnetcorehelloworld:$CIRCLE_BUILD_NUM
      # Push image to ECR
      - run: docker push 200053207227.dkr.ecr.ap-southeast-2.amazonaws.com/dotnetcorehelloworld:$CIRCLE_BUILD_NUM
